// <auto-generated />
using System;
using Csharp.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Csharp.Entites.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260531202639_AddedForeignKeyToCarCompany")]
    partial class AddedForeignKeyToCarCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Csharp.Entites.Model.CarCompany", b =>
                {
                    b.Property<Guid>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PersonEntityID")
                        .HasColumnType("char(36)");

                    b.HasKey("CarID");

                    b.HasIndex("PersonEntityID");

                    b.ToTable("CarCompanies");
                });

            modelBuilder.Entity("Csharp.Entites.Model.FoodCompany", b =>
                {
                    b.Property<Guid>("FoodCompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FoodCompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FoodCompanyID");

                    b.ToTable("FoodCompany");
                });

            modelBuilder.Entity("Csharp.Entites.Model.PersonEntity", b =>
                {
                    b.Property<Guid>("PersonEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PersonEntityID");

                    b.ToTable("PersonEntity");
                });

            modelBuilder.Entity("Csharp.Entites.Model.CarCompany", b =>
                {
                    b.HasOne("Csharp.Entites.Model.PersonEntity", "PersonEntity")
                        .WithMany()
                        .HasForeignKey("PersonEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
